web:
   image: web
   environment:
     - ALLOW_OVERRIDE=true
   ports:
     - "81:80"
   links:
     - db
   volumes:
     - ./app:/var/www/html/

db:
  image: mariadb:10.11
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: yKbfwxEjRNByKz
    MYSQL_USER: DgfG5eVE1pEb8B
    MYSQL_PASSWORD: yKbfwxEjRNByKz
    MYSQL_DATABASE: database
  ports:
    - "8889:3306"

phpmyadmin:
  image: phpmyadmin/phpmyadmin:5.2.1
  links:
    - db
  ports:
    - 8890:80
  environment:
    MYSQL_USER: DgfG5eVE1pEb8B
    MYSQL_PASSWORD: yKbfwxEjRNByKz
    MYSQL_DATABASE: database
